[project]
name = "resumelens"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "shubhangi sirsal", email = "shubhangisirsal@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "docx>=0.2.4",
    "pypdf>=6.16.2",
]

[project.scripts]
resumelens = "resumelens:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
